const Flight = require('../models/Flight');

async function seedFlights() {
  const count = await Flight.countDocuments();

  if (count === 0) {
    console.log('🌱 Seeding Flights collection...');

    await Flight.insertMany([
        {
            flightNumber: 'AA1001',
            origin: 'Manila (MNL)',
            destination: 'Hong Kong (HKG)',
            departureDate: new Date('2025-11-20'),
            departureTime: '08:30',
            arrivalTime: '10:45',
            aircraft: 'Airbus A321',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 148,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1002',
            origin: 'Manila (MNL)',
            destination: 'Singapore (SIN)',
            departureDate: new Date('2025-11-21'),
            departureTime: '09:15',
            arrivalTime: '12:45',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 186,
            price: 99,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1003',
            origin: 'Manila (MNL)',
            destination: 'Bangkok (BKK)',
            departureDate: new Date('2025-11-22'),
            departureTime: '10:30',
            arrivalTime: '13:45',
            aircraft: 'Airbus A320neo',
            travelClass: 'Economy',
            seatCapacity: 190,
            price: 188,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1004',
            origin: 'Manila (MNL)',
            destination: 'Tokyo (HND)',
            departureDate: new Date('2025-11-23'),
            departureTime: '07:00',
            arrivalTime: '12:00',
            aircraft: 'Boeing 787',
            travelClass: 'Premium Economy',
            seatCapacity: 250,
            price: 200,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1005',
            origin: 'Manila (MNL)',
            destination: 'Sydney (SYD)',
            departureDate: new Date('2025-11-24'),
            departureTime: '22:30',
            arrivalTime: '08:30',
            aircraft: 'Boeing 777',
            travelClass: 'Business',
            seatCapacity: 300,
            price: 350,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1006',
            origin: 'Manila (MNL)',
            destination: 'Seoul (ICN)',
            departureDate: new Date('2025-11-25'),
            departureTime: '11:15',
            arrivalTime: '15:00',
            aircraft: 'Airbus A330',
            travelClass: 'Economy',
            seatCapacity: 260,
            price: 175,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1007',
            origin: 'Manila (MNL)',
            destination: 'Ho Chi Minh City (SGN)',
            departureDate: new Date('2025-11-26'),
            departureTime: '13:00',
            arrivalTime: '15:45',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 120,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1008',
            origin: 'Manila (MNL)',
            destination: 'Taipei (TPE)',
            departureDate: new Date('2025-11-27'),
            departureTime: '09:30',
            arrivalTime: '11:45',
            aircraft: 'Airbus A321neo',
            travelClass: 'Economy',
            seatCapacity: 200,
            price: 250,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1009',
            origin: 'Manila (MNL)',
            destination: 'Shanghai (PVG)',
            departureDate: new Date('2025-11-28'),
            departureTime: '06:30',
            arrivalTime: '10:30',
            aircraft: 'Boeing 737 MAX',
            travelClass: 'Economy',
            seatCapacity: 190,
            price: 220,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1010',
            origin: 'Manila (MNL)',
            destination: 'Melbourne (MEL)',
            departureDate: new Date('2025-11-29'),
            departureTime: '20:00',
            arrivalTime: '06:30',
            aircraft: 'Boeing 787',
            travelClass: 'Business',
            seatCapacity: 280,
            price: 420,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1011',
            origin: 'Manila (MNL)',
            destination: 'Cebu (CEB)',
            departureDate: new Date('2025-11-30'),
            departureTime: '14:00',
            arrivalTime: '15:25',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 85,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1012',
            origin: 'Manila (MNL)',
            destination: 'Davao (DVO)',
            departureDate: new Date('2025-12-01'),
            departureTime: '07:45',
            arrivalTime: '09:30',
            aircraft: 'Airbus A320neo',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 95,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1013',
            origin: 'Manila (MNL)',
            destination: 'Beijing (PEK)',
            departureDate: new Date('2025-12-02'),
            departureTime: '08:00',
            arrivalTime: '12:30',
            aircraft: 'Boeing 737 MAX',
            travelClass: 'Economy',
            seatCapacity: 200,
            price: 210,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1014',
            origin: 'Manila (MNL)',
            destination: 'Osaka (KIX)',
            departureDate: new Date('2025-12-03'),
            departureTime: '09:45',
            arrivalTime: '14:00',
            aircraft: 'Boeing 787',
            travelClass: 'Premium Economy',
            seatCapacity: 250,
            price: 230,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1015',
            origin: 'Manila (MNL)',
            destination: 'Nagoya (NGO)',
            departureDate: new Date('2025-12-04'),
            departureTime: '10:30',
            arrivalTime: '14:45',
            aircraft: 'Airbus A321neo',
            travelClass: 'Economy',
            seatCapacity: 200,
            price: 215,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1016',
            origin: 'Manila (MNL)',
            destination: 'Hong Kong (HKG)',
            departureDate: new Date('2025-10-25'),
            departureTime: '08:00',
            arrivalTime: '10:30',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 148,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1017',
            origin: 'Manila (MNL)',
            destination: 'Singapore (SIN)',
            departureDate: new Date('2025-10-25'),
            departureTime: '09:30',
            arrivalTime: '12:30',
            aircraft: 'Boeing 737 MAX',
            travelClass: 'Economy',
            seatCapacity: 170,
            price: 99,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1018',
            origin: 'Manila (MNL)',
            destination: 'Bangkok (BKK)',
            departureDate: new Date('2025-10-31'),
            departureTime: '07:15',
            arrivalTime: '10:00',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 188,
            status: 'On Time'
          },
          {
            flightNumber: 'AA1019',
            origin: 'Manila (MNL)',
            destination: 'Tokyo (HND)',
            departureDate: new Date('2025-10-30'),
            departureTime: '08:00',
            arrivalTime: '13:00',
            aircraft: 'Boeing 787 Dreamliner',
            travelClass: 'Premium Economy',
            seatCapacity: 240,
            price: 200,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1020',
            origin: 'Manila (MNL)',
            destination: 'Sydney (SYD)',
            departureDate: new Date('2025-11-09'),
            departureTime: '23:00',
            arrivalTime: '09:30',
            aircraft: 'Airbus A350',
            travelClass: 'Business',
            seatCapacity: 300,
            price: 350,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1021',
            origin: 'Manila (MNL)',
            destination: 'Seoul (ICN)',
            departureDate: new Date('2025-11-03'),
            departureTime: '07:15',
            arrivalTime: '11:00',
            aircraft: 'Airbus A321',
            travelClass: 'Economy',
            seatCapacity: 200,
            price: 175,
            status: 'On Time'
          },
          {
            flightNumber: 'AA1022',
            origin: 'Manila (MNL)',
            destination: 'Ho Chi Minh City (SGN)',
            departureDate: new Date('2025-12-01'),
            departureTime: '10:00',
            arrivalTime: '13:00',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 190,
            price: 120,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA1023',
            origin: 'Manila (MNL)',
            destination: 'Taipei (TPE)',
            departureDate: new Date('2025-11-15'),
            departureTime: '08:00',
            arrivalTime: '10:30',
            aircraft: 'Boeing 737 MAX',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 250,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2001',
            origin: 'Manila (MNL)',
            destination: 'Tokyo (HND)',
            departureDate: new Date('2025-11-01'),
            departureTime: '08:00',
            arrivalTime: '13:00',
            aircraft: 'Airbus A321',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 200,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2002',
            origin: 'Tokyo (HND)',
            destination: 'Manila (MNL)',
            departureDate: new Date('2025-11-06'),
            departureTime: '09:30',
            arrivalTime: '14:15',
            aircraft: 'Airbus A321',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 205,
            status: 'On Time'
          },
          {
            flightNumber: 'AA2003',
            origin: 'Manila (MNL)',
            destination: 'Singapore (SIN)',
            departureDate: new Date('2025-11-03'),
            departureTime: '09:30',
            arrivalTime: '12:45',
            aircraft: 'Boeing 737 MAX',
            travelClass: 'Premium Economy',
            seatCapacity: 160,
            price: 180,
            status: 'On Time'
          },
          {
            flightNumber: 'AA2004',
            origin: 'Manila (MNL)',
            destination: 'Bangkok (BKK)',
            departureDate: new Date('2025-11-05'),
            departureTime: '07:15',
            arrivalTime: '10:45',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 170,
            price: 188,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2005',
            origin: 'Manila (MNL)',
            destination: 'Hong Kong (HKG)',
            departureDate: new Date('2025-11-07'),
            departureTime: '10:00',
            arrivalTime: '12:30',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 150,
            price: 148,
            status: 'On Time'
          },
          {
            flightNumber: 'AA2006',
            origin: 'Manila (MNL)',
            destination: 'Sydney (SYD)',
            departureDate: new Date('2025-11-09'),
            departureTime: '23:00',
            arrivalTime: '09:30',
            aircraft: 'Airbus A350',
            travelClass: 'Business',
            seatCapacity: 280,
            price: 350,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2007',
            origin: 'Manila (MNL)',
            destination: 'Seoul (ICN)',
            departureDate: new Date('2025-11-12'),
            departureTime: '07:15',
            arrivalTime: '11:00',
            aircraft: 'Boeing 787 Dreamliner',
            travelClass: 'Economy',
            seatCapacity: 220,
            price: 175,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2008',
            origin: 'Manila (MNL)',
            destination: 'Ho Chi Minh City (SGN)',
            departureDate: new Date('2025-11-15'),
            departureTime: '10:00',
            arrivalTime: '13:30',
            aircraft: 'Airbus A321',
            travelClass: 'Economy',
            seatCapacity: 190,
            price: 120,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2009',
            origin: 'Manila (MNL)',
            destination: 'Taipei (TPE)',
            departureDate: new Date('2025-11-17'),
            departureTime: '08:00',
            arrivalTime: '10:00',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 160,
            price: 250,
            status: 'On Time'
          },
          {
            flightNumber: 'AA2010',
            origin: 'Manila (MNL)',
            destination: 'Dubai (DXB)',
            departureDate: new Date('2025-11-20'),
            departureTime: '21:00',
            arrivalTime: '04:30',
            aircraft: 'Boeing 777',
            travelClass: 'First',
            seatCapacity: 300,
            price: 950,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2011',
            origin: 'Manila (MNL)',
            destination: 'Cebu (CEB)',
            departureDate: new Date('2025-11-22'),
            departureTime: '08:00',
            arrivalTime: '09:30',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 120,
            status: 'On Time'
          },
          {
            flightNumber: 'AA2012',
            origin: 'Cebu (CEB)',
            destination: 'Manila (MNL)',
            departureDate: new Date('2025-11-22'),
            departureTime: '10:30',
            arrivalTime: '12:00',
            aircraft: 'Airbus A320',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 125,
            status: 'On Time'
          },
          {
            flightNumber: 'AA2013',
            origin: 'Manila (MNL)',
            destination: 'Los Angeles (LAX)',
            departureDate: new Date('2025-11-25'),
            departureTime: '22:30',
            arrivalTime: '15:00',
            aircraft: 'Boeing 777',
            travelClass: 'Business',
            seatCapacity: 320,
            price: 980,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2014',
            origin: 'Manila (MNL)',
            destination: 'London (LHR)',
            departureDate: new Date('2025-11-27'),
            departureTime: '23:30',
            arrivalTime: '13:30',
            aircraft: 'Airbus A350',
            travelClass: 'First',
            seatCapacity: 300,
            price: 1100,
            status: 'Scheduled'
          },
          {
            flightNumber: 'AA2015',
            origin: 'Manila (MNL)',
            destination: 'Kuala Lumpur (KUL)',
            departureDate: new Date('2025-11-30'),
            departureTime: '06:30',
            arrivalTime: '09:00',
            aircraft: 'Boeing 737',
            travelClass: 'Economy',
            seatCapacity: 180,
            price: 150,
            status: 'On Time'
          }
    ]);

    console.log('✅ Flights successfully seeded!');
  } else {
    console.log('🛫 Flights already exist — skipping seeding.');
  }
}

module.exports = seedFlights;
